apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sonatype-iq-slackbot-deployment
  labels:
    app: sonatype-iq-slackbot
spec:
  replicas: 2
  revisionHistoryLimit: 10
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    metadata:
      labels:
        app: sonatype-iq-slackbot
        tier: service
    spec:
      containers:
      - image: local-mike:19447/michaelmworthington/sonatype-iq-slackbot:1.0.2
        name: sonatype-iq-slackbot
        env:
        - name: PORT
          value: "9000"
        ports:
        - containerPort: 9000
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /
            port: 9000
          initialDelaySeconds: 5
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 9000
          initialDelaySeconds: 5
          timeoutSeconds: 5       
